import { Task } from "@/components/gantt/types";

export const myTasks: Task[] = [
  {
    id: "t1",
    name: "Initial Planning",
    start: new Date(2025, 3, 20),
    end: new Date(2025, 4, 5),
    progress: 100,
    type: "task",
  },
  {
    id: "t2",
    name: "User Stories",
    start: new Date(2025, 4, 6),
    end: new Date(2025, 4, 10),
    progress: 75,
    dependencies: ["t1"],
    type: "task",
  },
  {
    id: "t3",
    name: "UI/UX Design",
    start: new Date(2025, 4, 11),
    end: new Date(2025, 4, 18),
    progress: 40,
    dependencies: ["t2"],
    type: "task",
  },
  {
    id: "t4",
    name: "API Dev",
    start: new Date(2025, 4, 15),
    end: new Date(2025, 4, 28),
    progress: 20,
    dependencies: ["t3"],
    type: "task",
  },
  {
    id: "t5",
    name: "Frontend Dev",
    start: new Date(2025, 4, 25),
    end: new Date(2025, 5, 10),
    progress: 10,
    dependencies: ["t3"],
    type: "task",
  },
  {
    id: "t6",
    name: "DB Setup",
    start: new Date(2025, 3, 22),
    end: new Date(2025, 4, 6),
    progress: 90,
    type: "task",
  },
  {
    id: "t7",
    name: "Mid-Project Review",
    start: new Date(2025, 4, 29),
    end: new Date(2025, 4, 30),
    progress: 0,
    type: "milestone",
    dependencies: ["t4", "t5"],
  },
  {
    id: "t8",
    name: "Documentation",
    start: new Date(2025, 4, 12),
    end: new Date(2025, 4, 20),
    progress: 15,
    dependencies: ["t2"],
    type: "task",
  },
  {
    id: "t9",
    name: "Final Testing",
    start: new Date(2025, 5, 11),
    end: new Date(2025, 5, 15),
    progress: 0,
    dependencies: ["t7"],
    type: "task",
  },
  {
    id: "t10",
    name: "Marketing Plan",
    start: new Date(2025, 4, 20),
    end: new Date(2025, 4, 27),
    progress: 5,
    dependencies: ["t1"],
    type: "task",
  },
  {
    id: "t11",
    name: "Pre-launch Prep",
    start: new Date(2025, 5, 16),
    end: new Date(2025, 5, 20),
    progress: 0,
    dependencies: ["t9", "t8"],
    type: "task",
  },
  {
    id: "t12",
    name: "Task Directly Below",
    start: new Date(2025, 3, 25),
    end: new Date(2025, 4, 3),
    progress: 50,
    dependencies: ["t1"],
    type: "task",
  },
  {
    id: "t13",
    name: "Phase 2 Planning",
    start: new Date(2025, 5, 21),
    end: new Date(2025, 5, 25),
    progress: 0,
    dependencies: ["t11"],
    type: "task",
  },
  {
    id: "t14",
    name: "Feature A Design",
    start: new Date(2025, 5, 26),
    end: new Date(2025, 5, 30),
    progress: 0,
    dependencies: ["t13"],
    type: "task",
  },
  {
    id: "t15",
    name: "Feature A Dev",
    start: new Date(2025, 6, 1),
    end: new Date(2025, 6, 10),
    progress: 0,
    dependencies: ["t14"],
    type: "task",
  },
  {
    id: "t16",
    name: "Feature B Design",
    start: new Date(2025, 6, 3),
    end: new Date(2025, 6, 8),
    progress: 0,
    dependencies: ["t13"],
    type: "task",
  },
  {
    id: "t17",
    name: "Feature B Dev",
    start: new Date(2025, 6, 9),
    end: new Date(2025, 6, 18),
    progress: 0,
    dependencies: ["t16"],
    type: "task",
  },
  {
    id: "t18",
    name: "Integration Testing",
    start: new Date(2025, 6, 19),
    end: new Date(2025, 6, 25),
    progress: 0,
    dependencies: ["t15", "t17"],
    type: "task",
  },
  {
    id: "t19",
    name: "User Acceptance Testing",
    start: new Date(2025, 6, 26),
    end: new Date(2025, 6, 30),
    progress: 0,
    dependencies: ["t18"],
    type: "task",
  },
  {
    id: "t20",
    name: "Final Bug Fixing",
    start: new Date(2025, 7, 1),
    end: new Date(2025, 7, 5),
    progress: 0,
    dependencies: ["t19"],
    type: "task",
  },
  {
    id: "t21",
    name: "Phase 2 Deployment",
    start: new Date(2025, 7, 6),
    end: new Date(2025, 7, 8),
    progress: 0,
    dependencies: ["t20"],
    type: "task",
  },
  {
    id: "t22",
    name: "Post-Launch Support",
    start: new Date(2025, 7, 9),
    end: new Date(2025, 7, 15),
    progress: 0,
    dependencies: ["t21"],
    type: "task",
  },
];
